language: php
php:
  - 5.4
  - 5.5
  - 5.6
mysql:
  database: database
  username: root
  encoding: utf8
install:
  # Install dependencies
  - ./bin/replicant/install.sh
  # install php packages required for running a web server from drush on php 5.3
  - sudo apt-get install -y --force-yes php5-cgi php5-mysql
env:
  - TRAVIS=true CI_NAME="travis-ci" COVERALLS_REPO_TOKEN="o0suJDRIoCDwgLP6ESFOP2AIokvmQ7e21"
before_script:
  # Start a web server on port 8080, run in the background; wait for initialization
  - ../vendor/drush/drush/drush runserver 127.0.0.1:8080 &
  - until netstat -an 2>/dev/null | grep '8080.*LISTEN'; do true; done
script:
  #- cd core
  #- mkdir -p build/logs
  #- ../../vendor/bin/phpunit --configuration shieldstore-phpunit.xml.dist --coverage-clover build/logs/clover.xml
  #- cd ../../../
  #- bin/behat
after_script:
  #- php ../../vendor/bin/coveralls -v
